# Generated by Django 4.2.5 on 2023-10-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTracker',
            fields=[
                ('trackingId', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('students_attending', models.CharField(max_length=256)),
            ],
        ),
    ]
