# Generated by Django 4.2.5 on 2023-10-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
